language: python
python:
  - "2.7.12"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install: "pip install -r requirements.txt"
script: lettuce
